use_frameworks!

platform :ios, '9.0'

target 'AAlertViewController_Example' do
  pod 'AAlertViewController', :path => '../'

  target 'AAlertViewController_Tests' do
    inherit! :search_paths

    
  end
end
